// This code can be used at dbdiagram.io
//// -- LEVEL 1
//// -- Tables and References

// Creating tables
Table item {
  id number [pk, not null]
  Name string [not null]
  Currently string [not null]
  Buy_Price string
  First_Bid string [not null]
  Number_of_Bids number [not null]
  Started string [not null]
  Ends string [not null]
  Seller string [not null]
  Description string [not null]
}

Ref: item.Seller - user.UserID

Ref: item.id < item_category.item_id
Ref: categories.id < item_category.category_id

Table item_category {
  item_id number 
  category_id number
}

Table categories {
  id number [pk]
  name string
}

Ref: item.id < item_bid.item_id
Ref: bid.id < item_bid.bid_id

Table item_bid {
  item_id number
  bid_id number
}

Table bid {
  id number [pk]
  Bidder string [not null]
  Time string [not null]
  Ammount string [not null]
}

Table user {
  UserID string [pk, not null]
  Location string
  Country string
  Rating number [not null]
}

Ref: bid.Bidder - user.UserID